FROM alpine:3.20 as base

RUN apk update && \
    apk add --no-cache \
    build-base \
    cmake \
    g++ \
    clang \
    llvm \
    compiler-rt \
    gdb \
    lldb

# Install googletest
RUN cd /tmp && \
    wget https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz && \
    tar xf v1.13.0.tar.gz && \
    cd googletest-1.13.0 && \
    mkdir install && \
    cd install && \
    cmake .. && \
    make && \
    make install && \
    cd ../../ && \
    rm -rf googletest-1.13.0 && \
    rm -rf v1.13.0.tar.g

# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    basicuser

# Set permissions for /usr/src/app
RUN mkdir -p /usr/src/app && chown -R basicuser:basicuser /usr/src/app

USER basicuser
WORKDIR /usr/src/app

ENTRYPOINT ["./docker/entrypoints/tests_entrypoint.sh"]