name: C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.cpp", "**.h", "Makefile" ]

jobs:
  linter-current:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
    - name: Install linters
      run: sudo apt-get install cppcheck clang-tidy
    - uses: actions/checkout@v4
    - name: Run cppcheck
      run: cppcheck src --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=unmatchedSuppression --check-level=exhaustive

  tests-current:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Install gtest from source
      run: sudo apt-get install libgtest-dev cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp ./lib/libgtest*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v4
    - name: Run all unit and integration tests
      run: make tests
      
  linter-ideal:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
      run docker build -t meatball/linter:0.1 -f ./docker/Dockerfile.linter .
      - name: Run docker container
      docker run --rm -t --name=meatball-linter --mount type=bind,source=.,target=/usr/src/app meatball/linter:0.1

  tests-ideal:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
      run docker build -t meatball/tests:0.1 -f ./docker/Dockerfile.tests .
      - name: Run docker container
      docker run --rm -t --name=meatball-tests --mount type=bind,source=.,target=/usr/src/app meatball/tests:0.1
